# Generated by Django 6.0.6 on 2026-06-29 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backtest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backtest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="backtest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backtests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
